name: .NET

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build DemoServer
      run: dotnet build DemoServer --configuration Release --no-restore
    - name: Build DemoClient
      run: dotnet build DemoClient --configuration Release --no-restore
